import 'package:flutter/material.dart';

/**
 * Created by Akash Kumar  of Eduxcellence on 5/18/2020.
 */
void main() {
  // main function  .....
  runApp(Text(
    // Text Widget  .....
    "Hello Flutter 1.7", // data ....
    textAlign: TextAlign.center, // alignment ....
    textDirection: TextDirection.ltr, // text direction  ....
  ));
}


