import 'package:flutter/material.dart';

void main() {
  // main function  .....
  runApp(Text(
    // Text Widget  .....
    "Hello Flutter 1.7", // data ....
    textAlign: TextAlign.center, // alignment ....
    textDirection: TextDirection.ltr, // text direction  ....
  ));
}


